// Common dog breeds offered by the breed combobox, alphabetical. Includes the
// popular crosses we see in daycare (Cockapoo, Labradoodle, …) plus generic
// crossbreed entries. This list is a convenience, not a constraint — the pet
// forms always allow a free-text breed, so missing entries never block entry.

export const DOG_BREEDS: readonly string[] = [
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Cocker Spaniel',
  'Australian Shepherd',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Bloodhound',
  'Border Collie',
  'Border Terrier',
  'Boston Terrier',
  'Boxer',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Cane Corso',
  'Cavachon',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Chihuahua',
  'Chow Chow',
  'Cockapoo',
  'Cocker Spaniel',
  'Crossbreed / Mixed Breed',
  'Dachshund (Miniature)',
  'Dachshund (Standard)',
  'Dalmatian',
  'Dobermann',
  'Dogue de Bordeaux',
  'English Setter',
  'English Springer Spaniel',
  'Flat-Coated Retriever',
  'Fox Terrier',
  'French Bulldog',
  'German Shepherd',
  'German Shorthaired Pointer',
  'Giant Schnauzer',
  'Golden Retriever',
  'Goldendoodle',
  'Great Dane',
  'Greyhound',
  'Havanese',
  'Hungarian Vizsla',
  'Irish Setter',
  'Irish Terrier',
  'Irish Wolfhound',
  'Jack Russell Terrier',
  'Jackapoo',
  'King Charles Spaniel',
  'Labradoodle',
  'Labrador Retriever',
  'Lakeland Terrier',
  'Leonberger',
  'Lhasa Apso',
  'Lurcher',
  'Maltese',
  'Maltipoo',
  'Mastiff',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Newfoundland',
  'Norfolk Terrier',
  'Old English Sheepdog',
  'Papillon',
  'Parson Russell Terrier',
  'Patterdale Terrier',
  'Pekingese',
  'Pointer',
  'Pomeranian',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Pug',
  'Puggle',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Rough Collie',
  'Saluki',
  'Samoyed',
  'Scottish Terrier',
  'Shar Pei',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Sprocker Spaniel',
  'Springador',
  'St. Bernard',
  'Staffordshire Bull Terrier',
  'Tibetan Terrier',
  'Weimaraner',
  'Welsh Corgi (Cardigan)',
  'Welsh Corgi (Pembroke)',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
];
