// Accounting & Exports Section

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { Badge } from '../../../components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../../components/ui/table';
import { DownloadSimple } from '@phosphor-icons/react';
import { useBillingFinanceSettingsStore } from '../store';

export function AccountingExportsSection() {
  const { exportConfigs, exports } = useBillingFinanceSettingsStore();

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Export Configurations</CardTitle>
          <CardDescription>
            Configure automated exports for accounting systems
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>Schedule</TableHead>
                <TableHead>Scope</TableHead>
                <TableHead>Last Export</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {exportConfigs.map((config) => (
                <TableRow key={config.id}>
                  <TableCell className="font-medium">{config.name}</TableCell>
                  <TableCell>
                    <Badge>{config.format.toUpperCase()}</Badge>
                  </TableCell>
                  <TableCell className="capitalize">{config.schedule.replace(/_/g, ' ')}</TableCell>
                  <TableCell className="capitalize">{config.scope.replace(/_/g, ' ')}</TableCell>
                  <TableCell>
                    {config.last_export_at
                      ? new Date(config.last_export_at).toLocaleString()
                      : 'Never'}
                  </TableCell>
                  <TableCell>
                    <Badge variant={config.is_active ? 'success' : 'secondary'}>
                      {config.is_active ? 'Active' : 'Inactive'}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {exportConfigs.length === 0 && (
            <div className="text-center py-8 text-muted-foreground">
              No export configurations defined.
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent Exports</CardTitle>
          <CardDescription>View and download recent financial exports</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Export Date</TableHead>
                <TableHead>Configuration</TableHead>
                <TableHead>Row Count</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {exports.slice(0, 10).map((exp) => (
                <TableRow key={exp.id}>
                  <TableCell>{new Date(exp.export_date).toLocaleString()}</TableCell>
                  <TableCell className="font-medium">{exp.configuration_id}</TableCell>
                  <TableCell>{exp.row_count}</TableCell>
                  <TableCell>{exp.generated_by}</TableCell>
                  <TableCell>
                    <Button size="sm" variant="outline">
                      <DownloadSimple className="h-4 w-4 mr-2" />
                      DownloadSimple
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {exports.length === 0 && (
            <div className="text-center py-8 text-muted-foreground">
              No exports generated yet.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
